on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n msprocloud -g msprocloud991b-rg --location "West Europe" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n msprocloud --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n msprocloud --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n msprocloud --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: msprocloud.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t msprocloud.azurecr.io/nextcloud:${{ github.sha }}
        docker push msprocloud.azurecr.io/nextcloud:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_nextcloud_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep nextcloud7372 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace nextcloud7372`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: nextcloud7372
        container-registry-url: msprocloud.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: nextclouddockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: nextcloud7372
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          msprocloud.azurecr.io/nextcloud:${{ github.sha }}
        imagepullsecrets: |
          nextclouddockerauth